# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test Web Application with Cypress
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, windows-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:    
    - name: Setup git in a container
      uses: actions/checkout@v2

    - name: Using Node.js ${{ matrix.node-version }} for the tests
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Installing Dependencies with ci
      run: npm ci
    
    - name: Installing the packages -> Cypress
      run: npm i cypress 
      
    - name: Running the tests
      run: npm test
